description: 3 nodes network
heat_template_version: '2015-04-30'
resources:
  0port0:
    properties:
      fixed_ips:
      - {ip_address: 10.20.0.10}
      network: {get_resource: Node0}
    type: OS::Neutron::Port
  0port1:
    properties:
      fixed_ips:
      - {ip_address: 10.40.0.40}
      network: {get_resource: Node1}
    type: OS::Neutron::Port
  1port0:
    properties:
      fixed_ips:
      - {ip_address: 10.20.0.40}
      network: {get_resource: Node0}
    type: OS::Neutron::Port
  1port1:
    properties:
      fixed_ips:
      - {ip_address: 10.60.0.10}
      network: {get_resource: Node2}
    type: OS::Neutron::Port
  2port0:
    properties:
      fixed_ips:
      - {ip_address: 10.40.0.10}
      network: {get_resource: Node1}
    type: OS::Neutron::Port
  2port1:
    properties:
      fixed_ips:
      - {ip_address: 10.60.0.40}
      network: {get_resource: Node2}
    type: OS::Neutron::Port
  Ne0:
    properties:
      cidr: 10.20.0.0/24
      host_routes:
      - {destination: 10.40.0.0/24, nexthop: 10.20.0.10}
      - {destination: 10.60.0.0/24, nexthop: 10.20.0.40}
      name: BERLIN
      network_id: {get_resource: Node0}
    type: OS::Neutron::Subnet
  Ne1:
    properties:
      cidr: 10.40.0.0/24
      host_routes:
      - {destination: 10.20.0.0/24, nexthop: 10.40.0.40}
      - {destination: 10.60.0.0/24, nexthop: 10.40.0.10}
      name: FRANKFURT
      network_id: {get_resource: Node1}
    type: OS::Neutron::Subnet
  Ne2:
    properties:
      cidr: 10.60.0.0/24
      host_routes:
      - {destination: 10.20.0.0/24, nexthop: 10.60.0.10}
      - {destination: 10.40.0.0/24, nexthop: 10.60.0.40}
      name: MUNICH
      network_id: {get_resource: Node2}
    type: OS::Neutron::Subnet
  Node0:
    properties: {name: BERLIN}
    type: OS::Neutron::Net
  Node1:
    properties: {name: FRANKFURT}
    type: OS::Neutron::Net
  Node2:
    properties: {name: MUNICH}
    type: OS::Neutron::Net
  ir0:
    properties: {name: ir0}
    type: OS::Neutron::Router
  ir1:
    properties: {name: ir1}
    type: OS::Neutron::Router
  ir2:
    properties: {name: ir2}
    type: OS::Neutron::Router
  iriA0:
    properties:
      port: {get_resource: 0port0}
      router_id: {get_resource: ir0}
    type: OS::Neutron::RouterInterface
  iriA1:
    properties:
      port: {get_resource: 1port0}
      router_id: {get_resource: ir1}
    type: OS::Neutron::RouterInterface
  iriA2:
    properties:
      port: {get_resource: 2port0}
      router_id: {get_resource: ir2}
    type: OS::Neutron::RouterInterface
  iriB0:
    properties:
      port: {get_resource: 0port1}
      router_id: {get_resource: ir0}
    type: OS::Neutron::RouterInterface
  iriB1:
    properties:
      port: {get_resource: 1port1}
      router_id: {get_resource: ir1}
    type: OS::Neutron::RouterInterface
  iriB2:
    properties:
      port: {get_resource: 2port1}
      router_id: {get_resource: ir2}
    type: OS::Neutron::RouterInterface
